repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [--fix, --extend-select, I] # Fix import sorting
      - id: ruff-format # Format code
      - id: ruff
        name: ruff-check
        args: [--no-fix] # Just check for issues
