# yaml-language-server: $schema=file:///workspaces/MatterTune/src/mattertune/finetune/main.MatterTunerConfig.schema.json

data:
    train:
        src:
    batch_size: 0
model:
    type: jmp
    properties:
      - type: energy
        loss:
            name: mae
      - type: forces
        loss:
            name: mae

    optimizer
    lr_scheduler
    ckpt_path:
    graph_computer
