[tool.poetry]
name = "mattertune"
version = "0.1.0"
description = ""
authors = ["Nima Shoghi <nimashoghi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nshtrainer = "*"
nshrunner = "*"
nshconfig = "*"
nshutils = "*"
numpy = "*"
torch = "*"
typing-extensions = "*"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.6"
ipykernel = "^6.29.5"
ipywidgets = "^8.1.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "standard"
deprecateTypingAliases = true
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
reportPrivateImportUsage = false

[tool.ruff.lint]
ignore = ["F722", "F821", "E731", "E741"]
