from __future__ import annotations

import argparse
import csv
import hashlib
import itertools
import json
import sys
from collections import Counter, defaultdict
from collections.abc import Iterable
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import rich
import torch
from ase import Atoms
from ase.io import iread
from rich.progress import track


EXAMPLE_DIR = Path(__file__).resolve().parent
REPO_ROOT = EXAMPLE_DIR.parents[1]
SRC_ROOT = REPO_ROOT / "src"
if SRC_ROOT.is_dir():
    sys.path.insert(0, str(SRC_ROOT))

from mattertune.main import load_finetuned_checkpoint  # noqa: E402

from component_reference import load_component_reference  # noqa: E402
from component_training import attach_component_reference  # noqa: E402


DATA_ROOT = Path("/net/csefiles/coc-fung-cluster/lingyu/electrolyte")
DEFAULT_TEST_FILE = DATA_ROOT / "Li_system_test_with_del.xyz"
DEFAULT_CHECKPOINT = (
    DATA_ROOT
    / "local_runs"
    / "elec-Li-withDel-03"
    / "20260507-113742-mattersim-withDel"
    / "checkpoints"
    / "MatterSim-v1.0.0-1M-withDel-best.ckpt"
)
DEFAULT_COMPONENT_REFERENCE = (
    DATA_ROOT
    / "local_runs"
    / "elec-Li-withDel-03"
    / "references"
    / "Li_system_train_with_del-MatterSim-v1.0.0-1M-component-residual-ridge-alpha1.0.json"
)


def structure_group(atoms: Atoms) -> str:
    return "normal" if "config_type" in atoms.info else "deleted"


def composition_signature(atoms: Atoms, *, include_li: bool = True) -> str:
    counts = Counter(atoms.get_chemical_symbols())
    if not include_li:
        counts.pop("Li", None)
    return " ".join(f"{element}{counts[element]}" for element in sorted(counts))


def coordinate_key(
    atoms: Atoms,
    *,
    remove_index: int | None = None,
    decimals: int = 6,
) -> str:
    """Key a structure by ordered symbols and rounded Cartesian coordinates.

    This intentionally keeps atom order. The deleted-Li datasets in this folder
    are expected to be generated by removing one Li from a parent frame without
    permuting the remaining atoms. If future data contains explicit pair ids,
    those should be preferred over this exact-coordinate fallback.
    """

    keep_indices = [
        index for index in range(len(atoms))
        if remove_index is None or index != remove_index
    ]
    symbols = [atoms[index].symbol for index in keep_indices]
    scale = 10**decimals
    position_grid = np.rint(atoms.get_positions()[keep_indices] * scale).astype(np.int64)
    digest = hashlib.sha1()
    digest.update("|".join(symbols).encode("utf-8"))
    digest.update(position_grid.tobytes())
    return digest.hexdigest()


def force_error_summary(force_gt: np.ndarray, force_pred: np.ndarray) -> dict[str, float]:
    force_error = force_pred - force_gt
    return {
        "force_component_mae_eV_A": float(np.mean(np.abs(force_error))),
        "force_component_rmse_eV_A": float(np.sqrt(np.mean(force_error**2))),
        "force_component_bias_eV_A": float(np.mean(force_error)),
    }


def infer_output_dir(checkpoint: Path) -> Path:
    if checkpoint.parent.name == "checkpoints":
        return checkpoint.parent.parent
    return checkpoint.parent / f"{checkpoint.stem}-eval"


def resolve_device(raw_device: str) -> str:
    if raw_device != "auto":
        return raw_device
    return "cuda:0" if torch.cuda.is_available() else "cpu"


def summarize_errors(
    *,
    energy_gt: np.ndarray,
    energy_pred: np.ndarray,
    natoms: np.ndarray,
    forces_gt: list[np.ndarray],
    forces_pred: list[np.ndarray],
    groups: list[str],
) -> dict[str, dict[str, float | int]]:
    metrics: dict[str, dict[str, float | int]] = {}
    for group_name in ["all"] + sorted(set(groups)):
        if group_name == "all":
            idx = np.arange(len(groups))
        else:
            idx = np.asarray([i for i, group in enumerate(groups) if group == group_name])
        if len(idx) == 0:
            continue

        e_err = energy_pred[idx] - energy_gt[idx]
        epa_err = energy_pred[idx] / natoms[idx] - energy_gt[idx] / natoms[idx]
        f_gt = np.vstack([forces_gt[i] for i in idx])
        f_pred = np.vstack([forces_pred[i] for i in idx])
        f_err = f_pred - f_gt

        metrics[group_name] = {
            "n_structures": int(len(idx)),
            "n_atoms": int(np.sum(natoms[idx])),
            "n_force_components": int(f_err.size),
            "energy_mae_eV": float(np.mean(np.abs(e_err))),
            "energy_rmse_eV": float(np.sqrt(np.mean(e_err**2))),
            "energy_bias_eV": float(np.mean(e_err)),
            "energy_per_atom_mae_eV": float(np.mean(np.abs(epa_err))),
            "energy_per_atom_rmse_eV": float(np.sqrt(np.mean(epa_err**2))),
            "energy_per_atom_bias_eV": float(np.mean(epa_err)),
            "force_component_mae_eV_A": float(np.mean(np.abs(f_err))),
            "force_component_rmse_eV_A": float(np.sqrt(np.mean(f_err**2))),
            "force_component_bias_eV_A": float(np.mean(f_err)),
        }
    return metrics


def summarize_record_subset(records: list[dict[str, Any]], indices: Iterable[int]) -> dict[str, float | int]:
    selected = [records[index] for index in indices]
    if not selected:
        return {"n_structures": 0}

    energy_error = np.asarray([row["energy_error_eV"] for row in selected], dtype=np.float64)
    energy_per_atom_error = np.asarray(
        [row["energy_per_atom_error_eV"] for row in selected],
        dtype=np.float64,
    )
    force_mae = np.asarray(
        [row["force_component_mae_eV_A"] for row in selected],
        dtype=np.float64,
    )
    force_rmse = np.asarray(
        [row["force_component_rmse_eV_A"] for row in selected],
        dtype=np.float64,
    )
    return {
        "n_structures": int(len(selected)),
        "energy_mae_eV": float(np.mean(np.abs(energy_error))),
        "energy_rmse_eV": float(np.sqrt(np.mean(energy_error**2))),
        "energy_bias_eV": float(np.mean(energy_error)),
        "energy_per_atom_mae_eV": float(np.mean(np.abs(energy_per_atom_error))),
        "energy_per_atom_rmse_eV": float(np.sqrt(np.mean(energy_per_atom_error**2))),
        "energy_per_atom_bias_eV": float(np.mean(energy_per_atom_error)),
        "mean_structure_force_component_mae_eV_A": float(np.mean(force_mae)),
        "mean_structure_force_component_rmse_eV_A": float(np.mean(force_rmse)),
    }


def summarize_records_by_key(
    records: list[dict[str, Any]],
    *,
    group: str,
    key_name: str,
) -> dict[str, dict[str, float | int]]:
    grouped: dict[str, list[int]] = defaultdict(list)
    for index, record in enumerate(records):
        if record["group"] != group:
            continue
        key = str(record.get(key_name, ""))
        if key:
            grouped[key].append(index)
    return {
        key: summarize_record_subset(records, indices)
        for key, indices in sorted(grouped.items())
    }


def summarize_exact_gap_pairs(
    records: list[dict[str, Any]],
    normal_candidates: dict[str, list[tuple[int, int]]],
    deleted_keys: dict[str, list[int]],
) -> tuple[dict[str, float | int | None], list[dict[str, Any]]]:
    gap_rows: list[dict[str, Any]] = []
    ambiguous_deleted = 0
    unmatched_deleted = 0

    for deleted_key, deleted_indices in deleted_keys.items():
        candidates = normal_candidates.get(deleted_key, [])
        if not candidates:
            unmatched_deleted += len(deleted_indices)
            continue
        if len(candidates) != 1:
            ambiguous_deleted += len(deleted_indices)
            continue

        normal_index, removed_li_index = candidates[0]
        normal = records[normal_index]
        for deleted_index in deleted_indices:
            deleted = records[deleted_index]
            dft_gap = float(normal["energy_gt_eV"] - deleted["energy_gt_eV"])
            pred_gap = float(normal["energy_pred_eV"] - deleted["energy_pred_eV"])
            gap_error = pred_gap - dft_gap
            gap_row = {
                "normal_structure_index": normal["structure_index"],
                "deleted_structure_index": deleted["structure_index"],
                "removed_li_index": removed_li_index,
                "config_type": normal.get("config_type", ""),
                "frame": normal.get("frame", ""),
                "normal_energy_gt_eV": normal["energy_gt_eV"],
                "deleted_energy_gt_eV": deleted["energy_gt_eV"],
                "normal_energy_pred_eV": normal["energy_pred_eV"],
                "deleted_energy_pred_eV": deleted["energy_pred_eV"],
                "dft_gap_eV": dft_gap,
                "pred_gap_eV": pred_gap,
                "gap_error_eV": gap_error,
                "normal_energy_error_eV": normal["energy_error_eV"],
                "deleted_energy_error_eV": deleted["energy_error_eV"],
            }
            gap_rows.append(gap_row)
            deleted["exact_pair_normal_structure_index"] = normal["structure_index"]
            deleted["exact_pair_removed_li_index"] = removed_li_index
            deleted["exact_pair_gap_error_eV"] = gap_error

    if gap_rows:
        gap_error = np.asarray([row["gap_error_eV"] for row in gap_rows], dtype=np.float64)
        normal_error = np.asarray(
            [row["normal_energy_error_eV"] for row in gap_rows],
            dtype=np.float64,
        )
        deleted_error = np.asarray(
            [row["deleted_energy_error_eV"] for row in gap_rows],
            dtype=np.float64,
        )
        common_mode_corr = (
            float(np.corrcoef(normal_error, deleted_error)[0, 1])
            if len(gap_rows) > 1
            else None
        )
        summary: dict[str, float | int | None] = {
            "n_exact_pairs": int(len(gap_rows)),
            "n_unmatched_deleted_structures": int(unmatched_deleted),
            "n_ambiguous_deleted_structures": int(ambiguous_deleted),
            "gap_mae_eV": float(np.mean(np.abs(gap_error))),
            "gap_rmse_eV": float(np.sqrt(np.mean(gap_error**2))),
            "gap_bias_eV": float(np.mean(gap_error)),
            "normal_deleted_energy_error_corr": common_mode_corr,
        }
    else:
        summary = {
            "n_exact_pairs": 0,
            "n_unmatched_deleted_structures": int(unmatched_deleted),
            "n_ambiguous_deleted_structures": int(ambiguous_deleted),
            "gap_mae_eV": None,
            "gap_rmse_eV": None,
            "gap_bias_eV": None,
            "normal_deleted_energy_error_corr": None,
        }

    return summary, gap_rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                seen.add(key)
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def save_parity_plot(
    output_path: Path,
    *,
    energy_gt: np.ndarray,
    energy_pred: np.ndarray,
    forces_gt: list[np.ndarray],
    forces_pred: list[np.ndarray],
    max_force_points: int,
    seed: int,
) -> None:
    f_gt = np.vstack(forces_gt).reshape(-1)
    f_pred = np.vstack(forces_pred).reshape(-1)
    if f_gt.size > max_force_points:
        rng = np.random.default_rng(seed)
        choice = rng.choice(f_gt.size, size=max_force_points, replace=False)
        f_gt = f_gt[choice]
        f_pred = f_pred[choice]

    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    ax = axes[0]
    ax.scatter(energy_gt, energy_pred, s=8, alpha=0.55)
    emin = min(float(energy_gt.min()), float(energy_pred.min()))
    emax = max(float(energy_gt.max()), float(energy_pred.max()))
    ax.plot([emin, emax], [emin, emax], color="k", linewidth=1.0)
    ax.set_xlim(emin, emax)
    ax.set_ylim(emin, emax)
    ax.set_xlabel("DFT energy (eV)")
    ax.set_ylabel("MLIP energy (eV)")
    ax.set_title("Energy")
    ax.set_aspect("equal", adjustable="box")

    ax = axes[1]
    ax.scatter(f_gt, f_pred, s=1, alpha=0.25)
    fmin = min(float(f_gt.min()), float(f_pred.min()))
    fmax = max(float(f_gt.max()), float(f_pred.max()))
    ax.plot([fmin, fmax], [fmin, fmax], color="k", linewidth=1.0)
    ax.set_xlim(fmin, fmax)
    ax.set_ylim(fmin, fmax)
    ax.set_xlabel("DFT force (eV/A)")
    ax.set_ylabel("MLIP force (eV/A)")
    ax.set_title("Force components")
    ax.set_aspect("equal", adjustable="box")

    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def predict_chunk(
    model: Any,
    atoms_chunk: list[Atoms],
) -> list[dict[str, torch.Tensor]]:
    data_list = [model.atoms_to_data(atoms, has_labels=False) for atoms in atoms_chunk]
    batch = model.collate_fn(data_list)
    batch = model.batch_to_device(batch, model.device)
    predictions = model.predict_step(batch=batch, batch_idx=0)
    if len(predictions) != len(atoms_chunk):
        raise RuntimeError(
            f"Prediction count mismatch: got {len(predictions)} for {len(atoms_chunk)} structures."
        )
    return predictions


def collect_predictions(
    *,
    atoms_chunk: list[Atoms],
    model: Any,
    energy_gt: list[float],
    energy_pred: list[float],
    forces_gt: list[np.ndarray],
    forces_pred: list[np.ndarray],
    natoms: list[int],
    groups: list[str],
    records: list[dict[str, Any]],
    normal_candidates: dict[str, list[tuple[int, int]]],
    deleted_keys: dict[str, list[int]],
    structure_indices: list[int],
    coordinate_decimals: int,
) -> None:
    predictions = predict_chunk(model, atoms_chunk)
    for structure_index, atoms, pred in zip(structure_indices, atoms_chunk, predictions, strict=True):
        gt_e = float(atoms.get_potential_energy())
        gt_f = np.asarray(atoms.get_forces(), dtype=np.float64)
        pred_e = float(pred["energy"].detach().cpu().numpy())
        pred_f = np.asarray(pred["forces"].detach().cpu().numpy(), dtype=np.float64)
        group = structure_group(atoms)
        natom = len(atoms)

        energy_gt.append(gt_e)
        forces_gt.append(gt_f)
        energy_pred.append(pred_e)
        forces_pred.append(pred_f)
        natoms.append(len(atoms))
        groups.append(group)

        force_metrics = force_error_summary(gt_f, pred_f)
        record_index = len(records)
        record: dict[str, Any] = {
            "structure_index": structure_index,
            "group": group,
            "natoms": natom,
            "composition": composition_signature(atoms),
            "nonli_composition": composition_signature(atoms, include_li=False),
            "config_type": atoms.info.get("config_type", ""),
            "frame": atoms.info.get("frame", ""),
            "energy_gt_eV": gt_e,
            "energy_pred_eV": pred_e,
            "energy_error_eV": pred_e - gt_e,
            "energy_per_atom_error_eV": pred_e / natom - gt_e / natom,
            **force_metrics,
        }
        records.append(record)

        if group == "normal":
            for atom_index, symbol in enumerate(atoms.get_chemical_symbols()):
                if symbol != "Li":
                    continue
                key = coordinate_key(
                    atoms,
                    remove_index=atom_index,
                    decimals=coordinate_decimals,
                )
                normal_candidates[key].append((record_index, atom_index))
        else:
            key = coordinate_key(atoms, decimals=coordinate_decimals)
            deleted_keys[key].append(record_index)


def evaluate_checkpoint(args: argparse.Namespace) -> dict[str, dict[str, float | int]]:
    checkpoint = Path(args.checkpoint)
    test_file = Path(args.test_file)
    output_dir = Path(args.output_dir) if args.output_dir else infer_output_dir(checkpoint)
    device = resolve_device(args.device)

    rich.print(f"Loading checkpoint: {checkpoint}")
    rich.print(f"Test file: {test_file}")
    rich.print(f"Device: {device}")

    model = load_finetuned_checkpoint(str(checkpoint), map_location=torch.device(device))
    feature_names, coefficients = load_component_reference(Path(args.component_reference))
    attach_component_reference(
        model,
        feature_names=feature_names,
        coefficients=coefficients,
        per_atom_energy_normalize=True,
    )
    model.eval()
    model.to_device(torch.device(device))
    model.hparams.using_partition = False

    energy_gt: list[float] = []
    energy_pred: list[float] = []
    forces_gt: list[np.ndarray] = []
    forces_pred: list[np.ndarray] = []
    natoms: list[int] = []
    groups: list[str] = []
    records: list[dict[str, Any]] = []
    normal_candidates: dict[str, list[tuple[int, int]]] = defaultdict(list)
    deleted_keys: dict[str, list[int]] = defaultdict(list)

    atoms_iter = iread(test_file, index=":")
    total = args.max_structures
    if args.max_structures is not None:
        atoms_iter = itertools.islice(atoms_iter, args.max_structures)

    atoms_chunk: list[Atoms] = []
    structure_indices: list[int] = []
    for structure_index, atoms in enumerate(
        track(atoms_iter, total=total, description="Evaluating test set")
    ):
        atoms_chunk.append(atoms)
        structure_indices.append(structure_index)
        if len(atoms_chunk) == args.batch_size:
            collect_predictions(
                atoms_chunk=atoms_chunk,
                model=model,
                energy_gt=energy_gt,
                energy_pred=energy_pred,
                forces_gt=forces_gt,
                forces_pred=forces_pred,
                natoms=natoms,
                groups=groups,
                records=records,
                normal_candidates=normal_candidates,
                deleted_keys=deleted_keys,
                structure_indices=structure_indices,
                coordinate_decimals=args.coordinate_match_decimals,
            )
            atoms_chunk = []
            structure_indices = []

    if atoms_chunk:
        collect_predictions(
            atoms_chunk=atoms_chunk,
            model=model,
            energy_gt=energy_gt,
            energy_pred=energy_pred,
            forces_gt=forces_gt,
            forces_pred=forces_pred,
            natoms=natoms,
            groups=groups,
            records=records,
            normal_candidates=normal_candidates,
            deleted_keys=deleted_keys,
            structure_indices=structure_indices,
            coordinate_decimals=args.coordinate_match_decimals,
        )

    if not groups:
        raise ValueError(f"No structures were read from {test_file}")

    metrics = summarize_errors(
        energy_gt=np.asarray(energy_gt, dtype=np.float64),
        energy_pred=np.asarray(energy_pred, dtype=np.float64),
        natoms=np.asarray(natoms, dtype=np.float64),
        forces_gt=forces_gt,
        forces_pred=forces_pred,
        groups=groups,
    )
    gap_summary, gap_rows = summarize_exact_gap_pairs(
        records,
        normal_candidates,
        deleted_keys,
    )
    metrics["_diagnostics"] = {
        "n_structures": int(len(records)),
        "n_normal_structures": int(sum(group == "normal" for group in groups)),
        "n_deleted_structures": int(sum(group == "deleted" for group in groups)),
        "n_normal_config_types": int(
            len({record["config_type"] for record in records if record["config_type"]})
        ),
        "n_deleted_nonli_compositions": int(
            len(
                {
                    record["nonli_composition"]
                    for record in records
                    if record["group"] == "deleted"
                }
            )
        ),
        "coordinate_match_decimals": int(args.coordinate_match_decimals),
    }
    metrics["normal_by_config_type"] = summarize_records_by_key(
        records,
        group="normal",
        key_name="config_type",
    )
    metrics["deleted_by_nonli_composition"] = summarize_records_by_key(
        records,
        group="deleted",
        key_name="nonli_composition",
    )
    metrics["gap_exact_coordinate_pairs"] = gap_summary

    output_dir.mkdir(parents=True, exist_ok=True)
    metrics_path = output_dir / args.metrics_name
    with metrics_path.open("w", encoding="utf-8") as handle:
        json.dump(metrics, handle, indent=4, sort_keys=True)

    if not args.no_plot:
        plot_path = output_dir / args.plot_name
        save_parity_plot(
            plot_path,
            energy_gt=np.asarray(energy_gt, dtype=np.float64),
            energy_pred=np.asarray(energy_pred, dtype=np.float64),
            forces_gt=forces_gt,
            forces_pred=forces_pred,
            max_force_points=args.max_force_plot_points,
            seed=args.seed,
        )
        rich.print(f"Saved parity plot to {plot_path}")

    if args.predictions_name:
        predictions_path = output_dir / args.predictions_name
        write_csv(predictions_path, records)
        rich.print(f"Saved per-structure predictions to {predictions_path}")

    if args.gap_pairs_name and gap_rows:
        gap_pairs_path = output_dir / args.gap_pairs_name
        write_csv(gap_pairs_path, gap_rows)
        rich.print(f"Saved exact-coordinate gap pairs to {gap_pairs_path}")

    rich.print(f"Saved test metrics to {metrics_path}")
    rich.print(json.dumps(metrics, indent=2, sort_keys=True))
    return metrics


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate a MatterTune MatterSim checkpoint on Li_system_test_with_del.xyz "
            "and report all/normal/deleted metrics."
        )
    )
    parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    parser.add_argument("--test_file", type=Path, default=DEFAULT_TEST_FILE)
    parser.add_argument("--component_reference", type=Path, default=DEFAULT_COMPONENT_REFERENCE)
    parser.add_argument(
        "--output_dir",
        type=Path,
        default=None,
        help=(
            "Directory for metrics/plot. Defaults to the checkpoint run directory "
            "when the checkpoint is under a checkpoints/ directory."
        ),
    )
    parser.add_argument(
        "--device",
        default="auto",
        help="Inference device, e.g. cuda:0, cuda:2, cpu, or auto.",
    )
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--max_structures", type=int, default=None)
    parser.add_argument("--metrics_name", default="test_metrics.json")
    parser.add_argument("--plot_name", default="test_parity.png")
    parser.add_argument("--predictions_name", default="test_predictions.csv")
    parser.add_argument("--gap_pairs_name", default="test_gap_exact_pairs.csv")
    parser.add_argument("--no_plot", action="store_true")
    parser.add_argument(
        "--coordinate_match_decimals",
        type=int,
        default=6,
        help=(
            "Decimal places used for exact deleted-Li coordinate matching. "
            "This is only a fallback when deleted structures lack explicit pair metadata."
        ),
    )
    parser.add_argument("--max_force_plot_points", type=int, default=200000)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    for required_path in (args.checkpoint, args.test_file, args.component_reference):
        if not Path(required_path).is_file():
            raise FileNotFoundError(required_path)
    if args.batch_size < 1:
        raise ValueError("--batch_size must be >= 1")
    return args


if __name__ == "__main__":
    evaluate_checkpoint(parse_args())
